### ISSUE TITLE
unacceptably large clock skew -> Error at dropPeer

### ISSUE THREAD

**Issue by Famicoman** [cjdelisle/cjdnsnode#4]
Running the snode and am getting time skews when connecting to cjd's node from the default config. Runs fine for about a minute, then a few minutes of time skew, then finally an error which looks like a crash and then the process automatically starts over. I have no v20 cjdns nodes connecting, I am just linking to cjd's snode.

Log excerpt:

```
ann:cad6c673c50b78b73138d28e2963a1d83be2a356660faf6564e27803ca2d0c8f6e20c6715c6b59347c8fbf594851d4ab336e110d824a5b41e607a06706026cbf
unacceptably large clock skew 99747764
ann:fe7c674bcf447a583df5e204a481048449055be7a4b80365eb0b7cdfd0fe024f177323cf7d7b0c31216dae96c53c91f5de84d1b0093e720064a47b30ad38d70c
unacceptably large clock skew 99746572
ann:9c5e0b755964c7aadb24499046a589b0bbb44a7b6dc2bb4e1a268fd1cb995c2f4f909b6457037bc476fb50a9f0703a979e08d424eb6d8162dd09aac074715d28
unacceptably large clock skew 99746121
ann:bf2af94db8e1cea8320113ae93fc65c14113252af8ceaa56c4fa74757cec51f2a0594380e43c6a9439f27fd74eb414d339e67e175235d0300e4d367c3eddef0f
unacceptably large clock skew 99745638
ann:8f32c93c70ef75b213e7b5a479c2a931c2ee8de86bdca9a12926c91fc4d0f2407b80cdac44f80b2bebca35d5b1363127486350b91f7e280e89d70d19ed01594c
unacceptably large clock skew 99741140
ann:1894c6d4efb9d47d72c7fd713dfe02aa9f60622e3f66c07862750441c375f8e88f0f8d78eac47fcc0c880bf58ca49bb2a7867fac7e8fc6d49417ee3b1cd042f1
unacceptably large clock skew 99739945
ann:66f5256b236e6e42c15b1e3ae5c0ff1fc0f908d247c1f4f0cf1a411dacdbd542889125a907e902b53039bf8bb47a6b53ac0ab54264b4afa616b678e19f862b17
unacceptably large clock skew 99739489
INV
need: e30a43042201b6d67bfb357713938af21e7150aa925c0c91b31da830994eb51365432e1f4398baf1db1d136105cc25fd3ab70f5143176a258176344b20abfe52
INV
need: d3eeba2d18ea4139189965efc0c624dee64688585675e9646b07aaa4a160606565fd9b1dedd8c6571fd33e87eaa3061f3ce2352f95d7bcdc03894f5706d092d7
INV
need: 5e995264ef3c4f4e9f7077389e7ed66f17cbde8f97c451b46815a0c874ed7b883aca86015197daf871068f02b31103771178c836002b84458fd33a528e909bef
INV
need: bcab7f541d949ae0df7943eb8198bb8ae2783d1be7c1451255d00955920292bf4e6d63196436dcef8f6f4b6835caf085fe6f0f9a99de6a5b3009cba51033543b
INV
need: 9a3c568e83bd0998e1288a8daedd2465dae5955fdb8577ad4442e0cc3c96f5ff9a2f7fd200599f3036c8ed0d4021ed140a50a545c96216b9601f384946902a09
INV
need: b22023758fd097b4fbd5aa131c9a332a2db5bee857511df9a72333abcd758ed414f3574d3d6a1ce773a64a6b924f379b5d541ab518e4342abac7cc0bb0b345c9
INV
need: fd892e38b0998e3113090fa6403198a5f92fa8cb457d559f3d7fa6fc112fbf52403039b0fef24d5bb6d11263fe70fc924569074a9b378a13f3384a0b84ca5627
INV
need: 025571ea5d71d692e2aa1f49beaf4811d52f703e5bd6017c50ffa64a48a6c96c95b9db4a9c5fe8176c3e7c385d770c08917e8ec2a8ce9817d42657eff5eb7f93
INV
need: 210a1b75af555411dc9ea5d9d7e9a36beaa7c48a92fb314c48871f16d311598f13317b897e5246c737134b86451762e4923d37eaded4c05f82d15dc954caab53
INV
need: b672060a5ee520b318dd6a9a2e39451ba36f07cf35d062357fa34d5f0a5a8130d3118b2abcd5092a489888dfdb06a3f8a5263e1bb55f7f3107f23c45f094fc54
INV
need: e86ab58e0342a1734bd015a40a1a8c5cc6241f350e509a1beccf3a121158e657c74eef6b5e8baddde51b946112a9475e1ace60ce71d0b479cee6d53b248a9b4a
INV
need: 62761a706e4c6b2a77bf2f55b390857be1f24a529400cede22f75ce62c1780614972c27a7e34fb55e708281fe2c24415ad8a19b4bb9da33927fde2d168886695
INV
need: 219b5656153fa4515f53d53a54fc7daafeabdab231650fc24d4c71e039b4ef592ddea498d7ee699342b024588aa303f96819ae1bbd25ece9301b2c93e0caa3f9
INV
need: ae55bf64830e740ee9491f75dca3ab4316f3b1a76a5ba9b1e8988d11fb48e0a7a024bc891d56dc4d72de29a74a5ca9ee3d20bcec5d49c4c959608dbe7f95528d
INV
need: e06764bcd479c644e957691fa9b0de5a805e82f0a1ed94293abaf4ef4fe7616cc329794b0887bf2bd66c8b2418cff21b780b0bebb1aa8517956556d58d297a53
>PING
INV
need: 46196ce4e3e25f5a65ee723dafc6c94c74ca0d6b8c42b7147bd6513ddda53772f1114b0ed8f362024fdc0a713f72ee3ce4a595ab6892018a0444ec81092a8fa4
INV
need: 1e18007acad345203f7c4a3bcd24dea5e54f1e0540483604f6f58447b894b6ae00a2d8d57826997488bdf7f25e4d06389b775bb2aa470f7a4da73a54d2e4b44f
INV
need: 85d9919a198f514ae67e7989924a936a64f078c158d8cb69eb975de6e506122c5ccfb0d516194f3d42fb44c8ee70f099f62c3c2e8b0fc5f1a1060fd5a51c6e4b
INV
need: 8ef4514fed67b92139fa8d58eee89b17a6f0257fbe7be5aa1683b043ad0c401dc0eb1a702474da9ece182f782fcf57e3ff30a210a0ae9a332539b9f4cf751ab5
INV
need: ac62ba03601e1f6120cfa84056ba5a5126cd350c40d236ebfe6765f0d0ec5d69a28f76564b7748554354552567bd9800f4969193efd240bbe28f2e006e0bc083
INV
need: d3609eaaf3ba6dd00229e634525c8cdf90d293c5f66d882b67ad8240cd086111c7d5d8df839e49e1793e5c9cb7b333165dd9f9be26702cf39ca14ead04e7f160
INV
need: 7035f695690702f8e3102b0b04622ad0c68c529237e592bc43b6582d7bdd43990d620ff11d3446af94df5fcc8cbfe919819c01eb69ce340e34596df9df05a0c9
INV
need: ad738e15077c837bc33cd3e2709ba2f0ea4d9b0e6f7516640d20a38608033df09314d5449ffaa0b6800b0924e8ab15eb85f5fa64206b4bff0ce918119e5db7ad
INV
need: 6e7d59b80dc058613bc2fe515becc3674cf2e282a41f98febccbc4b5e4c7d8a6b7678fa1efea7ad9b9da9f0261f7d58452e2f401c781b1f91452f4a610453489
INV
need: 5e3ac28bf5c97c9be84d771a3a35a6a0b5fec495ad71fd901c6b5acdb8f0ecc6c24a4096dd51149e26b826c843428e024a67e7108ef7e5fa1523838b4c0b231a
INV
need: efe68bc6878b3c0fa555fce49eff847d847ff5ecfd69c9b6fb597b82631d5543ab20d9b2cc33d8b2cd0aec2ca5d39bf68d7cdf7aa5c100e80f5ada26ffd35b14
INV
need: a8d859a37c378be1c31b04871b1bb0a6599861158a1bea2f53a4d11b79ec1e0d3ad5eaed5c404613811d600b16ea752bd6257bb5bf6840768a7f6ffe776ed90b
INV
need: c5c59613e1cea15ebd6b447c3e1fda66bc5596265dfb9bd618ef05f3405c87d2062d26a76d8f1df93a7cf22f3b5df04ce999bc8dead2fcfd1e982d72d6b0c808
INV
need: f9a85d0c2ab6dd6710b360cb4b33192c0026cd00c9db2677211938af7ca7a7e5b86c13e2c2adc2487fd14be1c2b25e308344924b98ab887737da74dca151012b
INV
need: 9e3f10b3fc085cf6cfd8868153df092fb365e93a57c1365171a48fec09b6e1c798b072eac06d484bd881062b3d78f503df7dcdde29b76445e8f6b64ba8d36a31
INV
need: 0188fc10d369ec5795175fd2bf0b2d7e0d246c6c62102a632f688fed58736df68ca97b9750f32f3e723b930da315a0d0b802e60459920aab771c89392e68a706
INV
need: ba5f46a7a123f124f8ef0f454e4aa185bab310709d3c243644a6cdf25be4fa58ddb0f89509d3b95e83a4d31b7f62f2f9a95d7ab7208484136ba8bfdb68290ae1
INV
need: 8e8c9aa1e60ff5fafa4e4ea82d721e813ca9a0e2321ff58de9eb9e802476a65e1082fba6dce0c12c44dc56aec8caf16ff67899cdf6118cb390f207cdd70b77e4
INV
need: ff6c48794190fb63a472712c46932b9787cc74dbc8c1dafb314d7079e2f4741fd2dcfd2e4c2bd31c5fbc937912887a5668cb70e9231aedb8cf9c6a74463cc7d3
INV
need: e70f9203a3256c506cb4510b472fd521279bb36cffba7bf52750194f9fe19d8c39f0fdd36a457cbea60f4cd44d3c4bd19a0eaed6247195317124ef0ad2be5d96
INV
need: b3174e1108a96c8852e06127f12974e248aca8a5f60601d2f72c024efcbf4f1c1bf8e065b23a0c50cf05ce5d33d58d7beb952a90a042bbfac828aff9d573b6f7
INV
need: 435b97615f290f7fafe309de25194b264812398620994d4f58b3672e58e733c1d112989d933b211b1ecb2024812a373c4af24347636ccc8eb4dced668134282b
INV
need: 2d7afeff1a94b6afc9075a13e31d87c98c18496aed0f186a404c8150cd0655b6b2616fd05d963b714e8bb455355ebbc41fcfaa0010917e3810859e7eb94c2eef
INV
need: 8555e3c7b845a3b6e1911cdb35d53113d8eef0594be226508180865a5d86a1ad941f3259b11f14ea7e32d829a69c568cb73d8441e184c5d757faa517e9601230
INV
need: 9a9fee306eb853a5cb0e4ad2321e3efd73c40d1ee3051d3494ec188caa4744d2ebd05e4b367a533d84fc4a90c77e0e7252a20f0c146d7f982a9cd92cce328bd4
Error
    at dropPeer (/opt/cjdnsnode/peer.js:34:17)
    at WebSocket.<anonymous> (/opt/cjdnsnode/peer.js:186:13)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at WebSocket.emitClose (/opt/cjdnsnode/node_modules/ws/lib/WebSocket.js:227:10)
    at _receiver.cleanup (/opt/cjdnsnode/node_modules/ws/lib/WebSocket.js:213:41)
    at Receiver.cleanup (/opt/cjdnsnode/node_modules/ws/lib/Receiver.js:522:15)
    at WebSocket.finalize (/opt/cjdnsnode/node_modules/ws/lib/WebSocket.js:213:22)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
Connected to ws://[fc50:71b5:aebf:7b70:6577:ec8:2542:9dd9]:3333/cjdnsnode_websocket
Connected to snode with version [1]
INV
need: 66ce198f1c5ac04b5757191f50a97460d07829405aa2f45ff0f65bb9b535a67cd6c74ad74e2d16f30f33b3791d21f7c1654cc066ef0e4a02dae139f06113162d
1202f54a8cc0f719795df1e6f9a9d0f5c2a83f22dfd69135ff9d4c3dd6ffd0f8b66371684705a029126be295e0f241ed8807c8e49567ac3ebd55528def7e9a89
55754caf7365fb818a8c7ad2dd0b3ee22560324e1d3285c0b38337a042e9b7b545643952807f383eb2eaf5f4514656c28ee5bb8fbb124f5a66facfe66dd89325
d06a4d350b1180f7c472da47f26e958b8e3ac616fa3a842ce122dd7771dd2b8fe32435e37ed6340fa37c542c08b68b08a8f1438f8c7eb1367ebf7e92eb81d866
```

Running Debian Jessie and node v6.11.0, Postgres 9.4.12.

Full logfile can be attached if needed.

**Comment by cjdelisle** [comment]
probably fixed by refactoring
